[package]
authors = ["Sean Cross <sean@xobs.io>"]
description = "Core kernel for Xous, including task switching and memory management"
edition = "2018"
name = "kernel"
version = "0.8.2"
resolver = "2"

[dependencies]
bitflags = "1.2.1"
# gdbstub branch "dev/0.6"
gdbstub = { git = "https://github.com/daniel5151/gdbstub.git", optional = true, default_features = false, rev = "9227dfd0b78db5b20859d13c890f6f47e597029e" }
gdbstub_arch = { git = "https://github.com/daniel5151/gdbstub.git", optional = true, rev = "9227dfd0b78db5b20859d13c890f6f47e597029e" }
sha3 = { default-features = false, version = "0.8.2" }
stats_alloc = { version = "0.1.8", optional = true }
xous-kernel = { package = "xous", path = "../xous-rs", features = [
    "forget-memory-messages",
] }

[target.'cfg(any(windows,unix))'.dev-dependencies]
xous-kernel = { package = "xous", path = "../xous-rs", features = [
    "forget-memory-messages",
    "processes-as-threads",
] }

[target.'cfg(not(any(windows, unix)))'.dependencies]
utralib = { path = "utralib" }

[target.'cfg(target_arch = "riscv32")'.dependencies]
riscv = { version = "0.5.6", path = "../imports/riscv-0.5.6" }

[features]
debug-print = []
gdbserver = ["gdbstub", "gdbstub_arch"]
print-panics = []
report-memory = ["stats_alloc"]
wrap-print = []
#default = ["print-panics", "debug-print", "wrap-print"]
default = ["print-panics", "gdbserver"]

[target.'cfg(any(windows, unix))'.dependencies]
crossbeam-channel = "0.5"
debug-here = "0.2.2"
hex = "0.4"
lazy_static = "1.4"
rand = "0.7"

[profile.release]
codegen-units = 1 # 1 better optimizations
debug = true      # symbols are nice and they don't increase the size on Flash
lto = "fat"
# panic = "abort" # Remove some panic information
# opt-level = 'z'  # Optimize for size instead of performance
